# Static Site Pattern - Development Environment
# Estimated Cost: $0/month (free tier)

metadata:
  project_name: ${PROJECT_NAME}
  environment: dev
  business_unit: ${BUSINESS_UNIT}
  cost_center: ${COST_CENTER}
  owner_email: ${OWNER_EMAIL}
  location: ${LOCATION:centralus}

resources:
  - type: static_web_app
    name: site
    config:
      sku: Free
      app_location: /
      output_location: dist
