apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runners
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/csGIT34/infrastructure-automation.git
    targetRevision: HEAD
    path: infrastructure/local-runners
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
