# API Backend Pattern - Development Environment
# Estimated Cost: $0/month (free tier)

metadata:
  project_name: ${PROJECT_NAME}
  environment: dev
  business_unit: ${BUSINESS_UNIT}
  cost_center: ${COST_CENTER}
  owner_email: ${OWNER_EMAIL}
  location: ${LOCATION:centralus}

resources:
  - type: function_app
    name: api
    config:
      runtime: ${RUNTIME:python}
      runtime_version: ${RUNTIME_VERSION:3.11}
      sku: Y1
      os_type: Linux
      app_settings:
        ENVIRONMENT: development

  - type: keyvault
    name: secrets
    config:
      sku: standard
      enable_rbac: true
