apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dnsmasq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/csGIT34/infrastructure-automation.git
    targetRevision: main
    path: infrastructure/local-runners/dnsmasq
  destination:
    server: https://kubernetes.default.svc
    namespace: dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
