apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-networking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/csGIT34/infrastructure-automation.git
    targetRevision: main
    path: infrastructure/local-runners/networking
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
