apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  lab.server: |
    lab.local:53 {
      errors
      log
      hosts {
        # Cluster nodes (external IPs on home network)
        10.1.1.60  k3s-master.lab.local master.lab.local
        10.1.1.61  k3s-worker-1.lab.local worker-1.lab.local
        10.1.1.62  k3s-worker-2.lab.local worker-2.lab.local
        # Traefik ingress (all apps route through here)
        10.1.1.230 traefik.lab.local
        10.1.1.230 argocd.lab.local
        10.1.1.230 workout.lab.local
        fallthrough
      }
      cache 30
    }
  forward.override: |
    forward . 1.1.1.1 1.0.0.1
