# Web App Pattern - Development Environment
# Estimated Cost: $0/month (free tier)
#
# Components:
# - Azure Functions (Consumption Plan) - Serverless API
# - Azure SQL (Free Tier) - Database
# - Storage Account (LRS) - File storage

metadata:
  project_name: ${PROJECT_NAME}
  environment: dev
  business_unit: ${BUSINESS_UNIT}
  cost_center: ${COST_CENTER}
  owner_email: ${OWNER_EMAIL}
  location: ${LOCATION:centralus}

resources:
  - type: function_app
    name: api
    config:
      runtime: ${RUNTIME:python}
      runtime_version: ${RUNTIME_VERSION:3.11}
      sku: Y1
      os_type: Linux
      app_settings:
        ENVIRONMENT: development
        DATABASE_HOST: ${PROJECT_NAME}-db.database.windows.net

  - type: azure_sql
    name: db
    config:
      sku: Free
      databases:
        - name: ${PROJECT_NAME}db
          sku: Free
          max_size_gb: 32

  - type: storage_account
    name: files
    config:
      tier: Standard
      replication: LRS
      containers:
        - name: uploads
          access_type: private
        - name: assets
          access_type: blob
