# Web App Pattern - Production Environment
# Estimated Cost: ~$150/month
#
# Components:
# - Azure Functions (Premium Plan) - High availability, VNet integration
# - Azure SQL (Standard S1) - Production-grade performance
# - Storage Account (GRS) - Geo-redundant storage
# - Key Vault - Secrets management

metadata:
  project_name: ${PROJECT_NAME}
  environment: prod
  business_unit: ${BUSINESS_UNIT}
  cost_center: ${COST_CENTER}
  owner_email: ${OWNER_EMAIL}
  location: ${LOCATION:centralus}

resources:
  - type: function_app
    name: api
    config:
      runtime: ${RUNTIME:python}
      runtime_version: ${RUNTIME_VERSION:3.11}
      sku: P1v2
      os_type: Linux
      app_settings:
        ENVIRONMENT: production
        DATABASE_HOST: ${PROJECT_NAME}-db.database.windows.net

  - type: azure_sql
    name: db
    config:
      sku: S1
      databases:
        - name: ${PROJECT_NAME}db
          sku: S1
          max_size_gb: 250
          zone_redundant: false
          backup_retention_days: 35

  - type: storage_account
    name: files
    config:
      tier: Standard
      replication: GRS
      versioning: true
      soft_delete_days: 30
      containers:
        - name: uploads
          access_type: private
        - name: assets
          access_type: blob

  - type: keyvault
    name: secrets
    config:
      sku: standard
      enable_rbac: true
      soft_delete_days: 90
