# Infrastructure GitOps Workflow Template
# Copy this file to your repository: .github/workflows/infrastructure.yaml
#
# Required secrets:
#   INFRA_APP_ID - GitHub App ID for Infrastructure Dispatch app
#   INFRA_APP_PRIVATE_KEY - GitHub App private key (PEM format)
#
# Supports pattern-based requests with t-shirt sizing (small/medium/large)
#
# Usage:
# 1. Create infrastructure.yaml in your repo root
# 2. Create a PR to see the plan preview
# 3. Merge to main to provision resources

name: Infrastructure GitOps

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure.yaml'
  pull_request:
    paths:
      - 'infrastructure.yaml'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-and-plan:
    runs-on: ubuntu-latest
    outputs:
      validation_result: ${{ steps.validate.outputs.result }}
      environment: ${{ steps.validate.outputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Validate infrastructure YAML
        id: validate
        run: |
          python << 'EOF'
          import yaml
          import json
          import sys
          import os

          infra_file = "infrastructure.yaml"

          if not os.path.exists(infra_file):
              print(f"::error::Infrastructure file not found: {infra_file}")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write("result=failed\n")
              sys.exit(1)

          try:
              with open(infra_file, 'r') as f:
                  config = yaml.safe_load(f)
          except yaml.YAMLError as e:
              print(f"::error::Invalid YAML syntax: {e}")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write("result=failed\n")
              sys.exit(1)

          errors = []

          # Only pattern-based requests are supported
          if 'pattern' not in config:
              errors.append("Missing 'pattern' field. Only pattern-based requests are supported.")

          # Validate metadata
          if 'metadata' not in config:
              errors.append("Missing 'metadata' section")
          else:
              metadata = config['metadata']
              required_meta = ['project', 'environment', 'business_unit', 'owners']
              for field in required_meta:
                  if field not in metadata:
                      errors.append(f"Missing metadata.{field}")

              # owners must be a list
              if 'owners' in metadata and not isinstance(metadata['owners'], list):
                  errors.append("metadata.owners must be a list of email addresses")

              # Validate environment
              env = metadata.get('environment', '')
              if env not in ['dev', 'staging', 'prod']:
                  errors.append(f"Invalid environment: {env}. Must be dev, staging, or prod")

          # Validate pattern
          if 'pattern' in config:
              valid_patterns = [
                  'keyvault', 'postgresql', 'mongodb', 'storage', 'function-app',
                  'sql-database', 'eventhub', 'aks-namespace', 'linux-vm', 'static-site',
                  'web-app', 'api-backend', 'microservice', 'data-pipeline'
              ]
              pattern = config.get('pattern', '')
              if pattern not in valid_patterns:
                  errors.append(f"Invalid pattern: {pattern}. Valid patterns: {', '.join(valid_patterns)}")

              # Validate config section
              if 'config' not in config:
                  errors.append("Missing 'config' section for pattern request")
              else:
                  cfg = config['config']
                  if 'name' not in cfg:
                      errors.append("Missing config.name")
                  if 'size' in cfg and cfg['size'] not in ['small', 'medium', 'large']:
                      errors.append(f"Invalid size: {cfg['size']}. Must be small, medium, or large")

          if errors:
              print("::error::Validation failed")
              for err in errors:
                  print(f"  - {err}")
              with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
                  f.write("result=failed\n")
                  f.write(f"errors={json.dumps(errors)}\n")
              sys.exit(1)

          environment = config.get('metadata', {}).get('environment', 'dev')
          print(f"Validation passed! Pattern: {config['pattern']}, Environment: {environment}")
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
              f.write("result=passed\n")
              f.write(f"environment={environment}\n")
          EOF

      - name: Generate Plan Preview
        id: plan
        run: |
          python << 'PLANEOF'
          import yaml
          import json
          import os

          with open("infrastructure.yaml", 'r') as f:
              config = yaml.safe_load(f)

          metadata = config.get('metadata', {})
          project = metadata.get('project', 'unknown')
          env = metadata.get('environment', 'dev')
          pattern = config.get('pattern', '')
          cfg = config.get('config', {})
          size = cfg.get('size', 'small')

          # Generate markdown preview
          preview = "## Infrastructure Plan Preview\n\n"
          preview += "### Pattern Request\n"
          preview += "| Property | Value |\n"
          preview += "|----------|-------|\n"
          preview += f"| Pattern | `{pattern}` |\n"
          preview += f"| Project | `{project}` |\n"
          preview += f"| Environment | `{env}` |\n"
          preview += f"| Size | `{size}` |\n"
          preview += f"| Business Unit | `{metadata.get('business_unit', 'N/A')}` |\n"
          preview += f"| Owners | `{', '.join(metadata.get('owners', []))}` |\n"
          preview += f"| Location | `{metadata.get('location', 'eastus')}` |\n\n"

          # Pattern-specific config
          preview += "### Configuration\n"
          preview += "| Setting | Value |\n"
          preview += "|---------|-------|\n"
          for key, value in cfg.items():
              preview += f"| {key} | `{value}` |\n"
          preview += "\n"

          # What will be created
          preview += "### What Will Be Created\n"
          pattern_components = {
              'keyvault': ['Key Vault', 'Security Groups', 'RBAC Assignments'],
              'postgresql': ['PostgreSQL Server', 'Database', 'Key Vault', 'Security Groups'],
              'mongodb': ['Cosmos DB (MongoDB)', 'Key Vault', 'Security Groups'],
              'storage': ['Storage Account', 'Blob Containers', 'Security Groups'],
              'function-app': ['Function App', 'App Service Plan', 'Storage Account', 'Key Vault', 'Security Groups'],
              'sql-database': ['SQL Server', 'Database', 'Key Vault', 'Security Groups'],
              'eventhub': ['Event Hub Namespace', 'Event Hub', 'Key Vault', 'Security Groups'],
              'aks-namespace': ['Kubernetes Namespace', 'Resource Quotas', 'Security Groups'],
              'linux-vm': ['Virtual Machine', 'Network Interface', 'Key Vault', 'Security Groups'],
              'static-site': ['Static Web App', 'Security Groups'],
              'web-app': ['Static Web App', 'Function App', 'Database', 'Key Vault', 'Security Groups'],
              'api-backend': ['Function App', 'Database', 'Key Vault', 'Security Groups'],
              'microservice': ['AKS Namespace', 'Event Hub', 'Storage', 'Key Vault', 'Security Groups'],
              'data-pipeline': ['Event Hub', 'Function App', 'Data Lake Storage', 'MongoDB', 'Key Vault', 'Security Groups']
          }
          components = pattern_components.get(pattern, ['Unknown components'])
          for component in components:
              preview += f"- {component}\n"
          preview += "\n"

          # Environment features
          preview += "### Environment Features\n"
          if env == 'prod':
              preview += "- Diagnostic logging enabled\n"
              preview += "- Access reviews enabled\n"
              preview += "- Geo-redundant backup (if applicable)\n"
              preview += "- Purge protection enabled\n"
          elif env == 'staging':
              preview += "- Diagnostic logging enabled\n"
              preview += "- Standard backup retention\n"
          else:
              preview += "- Development configuration\n"
              preview += "- Minimal backup retention\n"
          preview += "\n"

          preview += f"### Resource Group\n"
          preview += f"`rg-{project}-{env}`\n\n"
          preview += "---\n"
          preview += "**On merge to main**, these changes will be automatically provisioned.\n"

          with open('plan_preview.md', 'w') as f:
              f.write(preview)

          print(preview)
          PLANEOF

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let body = '## Infrastructure Plan\n\n';

            try {
              if (fs.existsSync('plan_preview.md')) {
                body = fs.readFileSync('plan_preview.md', 'utf8');
              } else {
                body += 'Infrastructure configuration validated successfully.\n\n';
                body += 'Merge this PR to provision the infrastructure.';
              }
            } catch (e) {
              body += 'Validation passed. See workflow summary for details.';
            }

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(c =>
              c.user.type === 'Bot' && c.body.includes('Infrastructure Plan')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: body
              });
            }

      - name: Create Job Summary
        if: always()
        run: |
          if [ -f plan_preview.md ]; then
            cat plan_preview.md >> $GITHUB_STEP_SUMMARY
          fi

  # Trigger provisioning on merge to main
  provision:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: validate-and-plan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.INFRA_APP_ID }}
          private-key: ${{ secrets.INFRA_APP_PRIVATE_KEY }}
          owner: csGIT34
          repositories: infrastructure-automation

      - name: Trigger Provisioning
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          # Base64 encode the YAML content to safely pass in JSON payload
          YAML_CONTENT=$(base64 -w0 infrastructure.yaml)

          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/csGIT34/infrastructure-automation/dispatches \
            -d "{
              \"event_type\": \"provision\",
              \"client_payload\": {
                \"repository\": \"${{ github.repository }}\",
                \"commit_sha\": \"${{ github.sha }}\",
                \"yaml_content\": \"$YAML_CONTENT\"
              }
            }"

          echo "Triggered infrastructure provisioning"
          echo ""
          echo "Request details:"
          echo "  Repository: ${{ github.repository }}"
          echo "  Commit: ${{ github.sha }}"

          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## Infrastructure Provisioning Triggered

          | Property | Value |
          |----------|-------|
          | Repository | \`${{ github.repository }}\` |
          | Commit | \`${{ github.sha }}\` |
          | Triggered By | \`${{ github.actor }}\` |

          Provisioning is running in the [infrastructure-automation](https://github.com/csGIT34/infrastructure-automation/actions) repository.
          EOF
